# Generated by Django 6.0.1 on 2026-08-07 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlygoal',
            name='unique_goal_per_user_category_month_year',
        ),
        migrations.AddConstraint(
            model_name='monthlygoal',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='unique_goal_per_user_category_month_year', nulls_distinct=False),
        ),
    ]
