# Generated by Django 6.0.1 on 2026-08-07 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
        ('goals', '0002_remove_monthlygoal_unique_goal_per_user_category_month_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlygoal',
            name='unique_goal_per_user_category_month_year',
        ),
        migrations.AddConstraint(
            model_name='monthlygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('user', 'category', 'month', 'year'), name='unique_goal_per_user_category_month_year'),
        ),
        migrations.AddConstraint(
            model_name='monthlygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('user', 'month', 'year'), name='unique_goal_per_user_null_category_month_year'),
        ),
    ]
