# Generated by Django 6.0.1 on 2026-09-25 04:02

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
        ('goals', '0003_remove_monthlygoal_unique_goal_per_user_category_month_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddConstraint(
            model_name='monthlygoal',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='goal_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='monthlygoal',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 2000), ('year__lte', 2100)), name='goal_year_range'),
        ),
    ]
