# Generated by Django 6.0.1 on 2026-05-08 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0003_bank_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('RENDA_FIXA', 'Renda Fixa'), ('RENDA_VARIAVEL', 'Renda Variavel'), ('CRIPTO', 'Cripto'), ('FUNDOS', 'Fundos')], max_length=20)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=150, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('expected_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('liquidity_type', models.CharField(blank=True, choices=[('DIARIA', 'Liquidez diaria'), ('VENCIMENTO', 'Somente no vencimento'), ('PERSONALIZADA', 'Liquidez personalizada')], max_length=20, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_assets', to='banks.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('APORTE', 'Aporte'), ('RESGATE', 'Resgate')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('movement_date', models.DateField()),
                ('register_cash_flow', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='investments.investmentasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
