# Generated by Django 6.0.1 on 2026-09-25 04:02

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_resync_balances'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentasset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='investmentmovement',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='investmentasset',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', 0)), name='investment_asset_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='investmentmovement',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='investment_movement_value_positive'),
        ),
    ]
