# Generated by Django 6.0.1 on 2026-01-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='categories.category'),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
