# Generated by Django 6.0.1 on 2026-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_category_payment_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
