# Generated by Django 6.0.1 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
