# Generated by Django 6.0.1 on 2026-05-15 17:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_creditcard_payment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
