# Generated by Django 6.0.1 on 2026-09-25 04:02

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def validate_required_payment_fields(apps, schema_editor):
    Payment = apps.get_model('payment', 'Payment')
    invalid_fields = Payment.objects.filter(
        Q(value__isnull=True) | Q(date_payment__isnull=True)
    ).count()
    if invalid_fields:
        raise RuntimeError(
            f'Cannot make payment fields required: {invalid_fields} legacy payments '
            'have a null value or date.'
        )


def reverse_required_payment_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
        ('payment', '0009_creditcard_closing_day_creditcard_due_day_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validate_required_payment_fields,
            reverse_required_payment_fields,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='parcelas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='payment_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('parcelas__gte', 1), ('parcelas__lte', 60)), name='payment_installments_range'),
        ),
    ]
