# Generated by Django 6.0.1 on 2026-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
