# Generated by Django 6.0.1 on 2026-06-30 13:16

from django.db import migrations


def backfill_initial_balance(apps, schema_editor):
    Bank = apps.get_model('banks', 'Bank')
    for bank in Bank.objects.all():
        bank.initial_balance = bank.balance
        bank.save(update_fields=['initial_balance'])


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_bank_initial_balance'),
    ]

    operations = [
        migrations.RunPython(backfill_initial_balance),
    ]
