# Generated by Django 6.0.1 on 2026-06-30 13:23

from django.db import migrations


def recalculate_stale_balances(apps, schema_editor):
    Bank = apps.get_model('banks', 'Bank')

    from django.db.models import Sum

    for bank in Bank.objects.all():
        inflows = bank.inflows.aggregate(Sum('value'))['value__sum'] or 0
        outflows = bank.outflows.aggregate(Sum('value'))['value__sum'] or 0
        expected = bank.initial_balance + inflows - outflows

        if bank.balance != expected:
            bank.initial_balance = 0
            bank.balance = inflows - outflows
            bank.save(update_fields=['initial_balance', 'balance'])


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_backfill_initial_balance'),
    ]

    operations = [
        migrations.RunPython(recalculate_stale_balances),
    ]
