LOGIN_SUCCESS = 'auth.login.success'
LOGIN_FAILURE = 'auth.login.failure'
LOGOUT_SUCCESS = 'auth.logout.success'
PASSWORD_CHANGE_SUCCESS = 'auth.password_change.success'
MFA_SETUP_SUCCESS = 'auth.mfa.setup.success'
MFA_VERIFY_SUCCESS = 'auth.mfa.verify.success'
MFA_VERIFY_FAILURE = 'auth.mfa.verify.failure'
PASSWORD_CHANGE_SUCCESS = 'auth.password_change.success'

INFLOW_CREATE = 'finance.inflow.create'
INFLOW_UPDATE = 'finance.inflow.update'
INFLOW_DELETE = 'finance.inflow.delete'

OUTFLOW_CREATE = 'finance.outflow.create'
OUTFLOW_UPDATE = 'finance.outflow.update'
OUTFLOW_DELETE = 'finance.outflow.delete'
TRANSFER_CREATE = 'finance.transfer.create'
PAYMENT_CREATE = 'finance.payment.create'
PAYMENT_MARK_PAID = 'finance.payment.mark_paid'
PAYMENT_MARK_UNPAID = 'finance.payment.mark_unpaid'
INVOICE_MARK_PAID = 'finance.invoice.mark_paid'
INVOICE_MARK_UNPAID = 'finance.invoice.mark_unpaid'
INVESTMENT_MOVEMENT_CREATE = 'finance.investment.movement.create'
REPORT_GENERATE = 'report.generate'
