"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    CSRF_TRUSTED_ORIGINS=(list, []),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
ENVIRONMENT = env('DJANGO_ENV', default='dev')
if ENVIRONMENT not in {'dev', 'docker', 'test', 'prd'}:
    raise RuntimeError(f'DJANGO_ENV invalido: {ENVIRONMENT}')

SECRET_KEY = env('SECRET_KEY', default='')
if not SECRET_KEY:
    raise RuntimeError(
        'SECRET_KEY nao definida. Configure a variavel de ambiente '
        'SECRET_KEY no arquivo .env'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = [
    host.strip()
    for host in env('ALLOWED_HOSTS')
    if host.strip() and host.strip() != '0.0.0.0'
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in env('CSRF_TRUSTED_ORIGINS')
    if origin.strip()
]

if ENVIRONMENT == 'prd':
    if DEBUG:
        raise RuntimeError('DEBUG deve ser False em producao.')
    if SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 50:
        raise RuntimeError('SECRET_KEY de producao deve ser forte e unica.')
    if not os.environ.get('ALLOWED_HOSTS') or not ALLOWED_HOSTS:
        raise RuntimeError('ALLOWED_HOSTS deve ser definido em producao.')
    if any('*' in host for host in ALLOWED_HOSTS):
        raise RuntimeError('ALLOWED_HOSTS nao aceita wildcard em producao.')
    if not CSRF_TRUSTED_ORIGINS:
        raise RuntimeError('CSRF_TRUSTED_ORIGINS deve ser definido em producao.')
    if any('*' in origin or not origin.startswith('https://') for origin in CSRF_TRUSTED_ORIGINS):
        raise RuntimeError('CSRF_TRUSTED_ORIGINS deve conter origens HTTPS exatas.')

    database_url = env('DATABASE_URL', default='')
    if not database_url.startswith(('postgres://', 'postgresql://')):
        raise RuntimeError('DATABASE_URL de producao deve usar PostgreSQL.')

    celery_broker_url = env('CELERY_BROKER_URL', default='')
    if not celery_broker_url.startswith('amqp://') or 'guest:' in celery_broker_url:
        raise RuntimeError('CELERY_BROKER_URL de producao deve usar RabbitMQ com credencial segura.')

    if not env('REDIS_URL', default='').startswith('redis://'):
        raise RuntimeError('REDIS_URL de producao deve usar Redis.')


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'dj_celery_panel',
    'django_celery_beat',
    'django_celery_results',

    'app',
    'accounts',
    'authentication',
    'banks',
    'categories',
    'inflows',
    'outflows',
    'transfers',
    'payment',
    'signatures',
    'investments',
    'reports',
    'goals',
    'auditing',
    'integrations',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.MFAMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.SecurityHeadersMiddleware',
    'auditing.middleware.RequestIDMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.total_balance',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default='sqlite:///db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Number formatting in pt-BR style (e.g. 1.000,00)
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'jwt_token': '10/min',
        'jwt_refresh': '30/min',
        'jwt_verify': '60/min',
        'jwt_logout': '10/min',
    },
}


AUTH_RATE_LIMITS = {
    'login': {'limit': 10, 'window_seconds': 300},
    'mfa_setup': {'limit': 8, 'window_seconds': 300},
    'mfa_verify': {'limit': 8, 'window_seconds': 300},
    'invite_accept': {'limit': 10, 'window_seconds': 3600},
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


os.environ["DJANGO_RUNSERVER_HIDE_WARNING"] = "true"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'app' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if ENVIRONMENT in {'docker', 'prd'}
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}


# Trust X-Forwarded-Proto from reverse proxy when not in debug mode.
# Prevents redirect loops behind Traefik in production (DEBUG=False).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_REDIRECT_EXEMPT = [r'^/health/$', r'^/ready/$']

# Strict transport security and secure cookies only in real production.
if ENVIRONMENT == 'prd':
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
CONTENT_SECURITY_POLICY = '; '.join([
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    "form-action 'self'",
])
PERMISSIONS_POLICY = ', '.join([
    'camera=()',
    'display-capture=()',
    'geolocation=()',
    'microphone=()',
])
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200
AUDIT_RETENTION_DAYS = 365
BACKUP_RETENTION_DAYS = 30

# WhatsApp / Evolution API
EVOLUTION_API_URL = env('EVOLUTION_API_URL', default='http://localhost:8080')
EVOLUTION_API_KEY = env('EVOLUTION_API_KEY', default='')
EVOLUTION_INSTANCE_NAME = env('EVOLUTION_INSTANCE_NAME', default='gaw-finance')
WHATSAPP_WEBHOOK_SECRET = env('WHATSAPP_WEBHOOK_SECRET', default='')

# LLM
LLM_PROVIDER = env('LLM_PROVIDER', default='opencode')
if LLM_PROVIDER not in {'opencode', 'openai'}:
    raise RuntimeError(f'LLM_PROVIDER invalido: {LLM_PROVIDER}')
LLM_API_KEY = env('LLM_API_KEY', default='')
LLM_BASE_URL = env('LLM_BASE_URL', default='')
LLM_MODEL = env('LLM_MODEL', default='gpt-4o-mini')

# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='amqp://guest:guest@localhost:5672//')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_DEFAULT_QUEUE_DURABLE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'close-past-invoices': {
        'task': 'app.close_past_invoices',
        'schedule': timedelta(hours=1),
    },
    'generate-signature-charges': {
        'task': 'app.generate_signature_charges',
        'schedule': timedelta(hours=1),
    },
    'prune-audit-events': {
        'task': 'auditing.prune_audit_events',
        'schedule': timedelta(days=1),
    },
}


# Cache (Redis)
if ENVIRONMENT in {'docker', 'prd'}:
    cache_backend = 'django_redis.cache.RedisCache'
else:
    cache_backend = 'django.core.cache.backends.locmem.LocMemCache'

CACHES = {
    'default': {
        'BACKEND': cache_backend,
        'LOCATION': env('REDIS_URL', default='redis://localhost:6379/0'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'auditing.logging.JSONFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
