# Generated by Django 6.0.1 on 2026-01-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('categories', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payment.payment')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank', to='banks.bank')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
