# Generated by Django 6.0.1 on 2026-01-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('categories', '0001_initial'),
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='Payment',
        ),
        migrations.AlterField(
            model_name='outflow',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='banks.bank'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='categories.category'),
        ),
    ]
