# Generated by Django 6.0.1 on 2026-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_remove_outflow_payment_alter_outflow_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='description',
        ),
        migrations.AddField(
            model_name='outflow',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
