# Generated by Django 6.0.1 on 2026-09-25 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_resync_balances'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='bank_transfer_value_positive'),
        ),
    ]
