# Generated by Django 6.0.8 on 2026-09-26 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('instance_name', models.CharField(default='gaw-finance', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vinculo WhatsApp',
                'verbose_name_plural': 'Vinculos WhatsApp',
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saida')], max_length=3)),
                ('phone', models.CharField(max_length=20)),
                ('raw_body', models.JSONField(blank=True, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('interpreted_intent', models.CharField(blank=True, max_length=20, null=True)),
                ('result_status', models.CharField(default='pending', max_length=20)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='integrations.whatsappbinding')),
            ],
            options={
                'verbose_name': 'Log de mensagem WhatsApp',
                'verbose_name_plural': 'Logs de mensagens WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
