# Generated by Django 6.0.1 on 2026-01-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='banks.bank'),
        ),
    ]
