# Generated by Django 6.0.1 on 2026-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_alter_inflow_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflow',
            name='description',
        ),
        migrations.AddField(
            model_name='inflow',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
