# Generated by Django 6.0.1 on 2026-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_remove_inflow_description_inflow_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
