# Generated by Django 6.0.1 on 2026-01-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0004_inflow_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflow',
            name='balance',
        ),
    ]
