# Generated by Django 6.0.1 on 2026-09-25 04:02

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_resync_balances'),
        ('inflows', '0006_inflow_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='inflow',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='inflow_value_positive'),
        ),
    ]
