# Generated by Django 6.0.1 on 2026-05-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0002_bank_balance'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('billing_day', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_month', models.PositiveIntegerField(blank=True, null=True)),
                ('last_generated_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='banks.bank')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='categories.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
