# Generated by Django 6.0.1 on 2026-07-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_creditcard_credit_limit'),
        ('signatures', '0002_signature_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='bank',
        ),
        migrations.AddField(
            model_name='signature',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='payment.creditcard'),
        ),
    ]
