# Generated by Django 6.0.1 on 2026-09-25 04:02

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
        ('payment', '0010_alter_payment_parcelas_alter_payment_value_and_more'),
        ('signatures', '0003_remove_signature_bank_signature_credit_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='billing_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='signature',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='signature_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.CheckConstraint(condition=models.Q(('billing_day__gte', 1), ('billing_day__lte', 31)), name='signature_billing_day_range'),
        ),
    ]
