# Generated by Django 6.0.1 on 2026-09-25 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_payment_parcelas_alter_payment_value_and_more'),
        ('signatures', '0004_alter_signature_billing_day_alter_signature_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('reference_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_charge', to='payment.payment')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='signatures.signature')),
            ],
            options={
                'ordering': ['-reference_year', '-reference_month', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('signature', 'reference_year', 'reference_month'), name='uniq_signature_charge_per_month'), models.CheckConstraint(condition=models.Q(('reference_month__gte', 1), ('reference_month__lte', 12)), name='signature_charge_month_range'), models.CheckConstraint(condition=models.Q(('reference_year__gte', 2000), ('reference_year__lte', 2100)), name='signature_charge_year_range')],
            },
        ),
    ]
